l3file("https://cdn.statically.io/gh/hamdaniazzah/hamdaniazzah.github.io/master/l3/css/post_3.css", "css")
l3file("https://cdn.ampproject.org/v0/amp-youtube-0.1.js", "js")
l3file("https://cdn.ampproject.org/v0/amp-iframe-0.1.js", "js")
l3file("https://cdn.ampproject.org/v0/amp-facebook-like-0.1.js", "js")
l3file("https://cdn.ampproject.org/v0/amp-social-share-0.1.js", "js")
l3file("https://cdn.statically.io/gh/hamdaniazzah/hamdaniazzah.github.io/master/l3/js/post_3.js", "js")
