document.getElementById('cj_a').innerHTML = 'A'
document.getElementById('cj_b').innerHTML = 'B'
document.getElementById('cj_c').innerHTML = 'C'
document.getElementById('cj_d').innerHTML = 'D'
document.getElementById('cj_e').innerHTML = 'E'
document.getElementById('cj_f').innerHTML = 'F'
document.getElementById('cj_g').innerHTML = 'G'
document.getElementById('cj_h').innerHTML = 'H'
document.getElementById('cj_i').innerHTML = 'I'
document.getElementById('cj_j').innerHTML = 'J'
document.getElementById('cj_k').innerHTML = 'K'
document.getElementById('cj_l').innerHTML = 'L'
document.getElementById('cj_m').innerHTML = 'M'
document.getElementById('cj_n').innerHTML = 'N'
document.getElementById('cj_o').innerHTML = 'O'
document.getElementById('cj_p').innerHTML = 'P'
document.getElementById('cj_q').innerHTML = 'Q'
document.getElementById('cj_r').innerHTML = 'R'
document.getElementById('cj_s').innerHTML = 'S'
document.getElementById('cj_t').innerHTML = 'T'
document.getElementById('cj_u').innerHTML = 'U'
document.getElementById('cj_v').innerHTML = 'V'
document.getElementById('cj_w').innerHTML = 'W'
document.getElementById('cj_x').innerHTML = 'X'
document.getElementById('cj_y').innerHTML = 'Y'
document.getElementById('cj_z').innerHTML = 'Z'
document.getElementById('cj_hash').innerHTML = '#'

document.getElementById('ca_a').innerHTML = 'A'
document.getElementById('ca_b').innerHTML = 'B'
document.getElementById('ca_c').innerHTML = 'C'
document.getElementById('ca_d').innerHTML = 'D'
document.getElementById('ca_e').innerHTML = 'E'
document.getElementById('ca_f').innerHTML = 'F'
document.getElementById('ca_g').innerHTML = 'G'
document.getElementById('ca_h').innerHTML = 'H'
document.getElementById('ca_i').innerHTML = 'I'
document.getElementById('ca_j').innerHTML = 'J'
document.getElementById('ca_k').innerHTML = 'K'
document.getElementById('ca_l').innerHTML = 'L'
document.getElementById('ca_m').innerHTML = 'M'
document.getElementById('ca_n').innerHTML = 'N'
document.getElementById('ca_o').innerHTML = 'O'
document.getElementById('ca_p').innerHTML = 'P'
document.getElementById('ca_q').innerHTML = 'Q'
document.getElementById('ca_r').innerHTML = 'R'
document.getElementById('ca_s').innerHTML = 'S'
document.getElementById('ca_t').innerHTML = 'T'
document.getElementById('ca_u').innerHTML = 'U'
document.getElementById('ca_v').innerHTML = 'V'
document.getElementById('ca_w').innerHTML = 'W'
document.getElementById('ca_x').innerHTML = 'X'
document.getElementById('ca_y').innerHTML = 'Y'
document.getElementById('ca_z').innerHTML = 'Z'
document.getElementById('ca_hash').innerHTML = '#'

function c_judul(){
document.getElementById("c_judul")
document.getElementById("c_artisnya").style.display="none";
document.getElementById("c_judulnya").style.display="block";}
function c_artis(){
document.getElementById("c_artis")
document.getElementById("c_judulnya").style.display="none";
document.getElementById("c_artisnya").style.display="block";}
